config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from filebrowser.sites import site

# from . import settings


urlpatterns = [
    path('admin/filebrowser/', site.urls),
    path('grappelli/', include('grappelli.urls')),
    path('admin/', admin.site.urls),
    # path('iyanuashiri/', admin.site.urls),
    # path('iyanuashiri/filebrowser/', site.urls),
    path('', include('meethub.events.urls'), name='events'),
    
    path('', include('meethub.accounts.urls')),
    # path('tinymce/', include('tinymce.urls')),
    path('', include('meethub.profile.urls'), name='profile'),
    path('', include('meethub.actions.urls')),
    path('', include('meethub.comments.urls')),

    # path('api/v1/', include('apiv1.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

meethub/accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from meethub.accounts import views

app_name = 'accounts'
urlpatterns = [
    path('', views.HomePageView.as_view(), name='homepage'),
    path('accounts/login/', auth_views.LoginView.as_view(), name='login'),
    path('accounts/logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('accounts/signup/', views.SignUp.as_view(), name='signup'),
]

meethub/actions/urls.py
from django.urls import path

from meethub.actions import views


app_name = 'actions'
urlpatterns = [
    path('notifications/', views.NotificationList.as_view(), name='notification_list')
]

meethub/comments/urls.py
from django.urls import path
from meethub.comments import views


app_name = 'comments'
urlpatterns = [
    path('comments/<int:pk>/delete/', views.CommentDelete.as_view(), name='comment-delete'),
    path('comments/<comment_id>/<event_id>/detail/', views.comment_detail, name='comment-detail'),

]

meethub/events/urls.py
from django.urls import path
from meethub.events import views

app_name = 'events'
urlpatterns = [
    path('events/', views.EventList.as_view(), name='event-list'),
    path('events/<int:pk>/', views.EventDetail.as_view(), name='event-detail'),
    path('events/new/', views.EventCreate.as_view(), name='event-create' ),
    path('events/<int:pk>/delete', views.EventDelete.as_view(), name='event-delete'),
    path('events/<int:pk>/update', views.EventUpdate.as_view(), name='event-update'),
    path('events/<event_id>/attend/', views.attend_event, name='attend_event'),
    path('events/<event_id>/not_attend/', views.not_attend_event, name='not_attend_event'),

]

meethub/profile/urls.py
from django.urls import path


from meethub.profile import views


app_name = 'profile'
urlpatterns = [
    path('edit/', views.edit_profile, name='edit'),
    path('detail/<int:pk>/', views.UserDetail.as_view(), name='detail'),
]

meethub/events/models.py
from django.db import models
from django.conf import settings
from django.shortcuts import reverse
from django.contrib.auth.models import User

from tinymce import models as tinymce_models 

from meethub.accounts.models import Account


# Create your models here.


class Category(models.Model):
    name = models.CharField(max_length=50, unique=True)
    description = models.TextField(max_length=500)

    class Meta:
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name


class Event(models.Model):
    name = models.CharField(max_length=50)
    details = tinymce_models.HTMLField()
    venue = models.CharField(max_length=200)
    date = models.DateField(help_text='Please use the following format: <em>YYYY-MM-DD</em>.')
    time = models.TimeField(help_text='Please use the following format: <em>HH:MM:SS<em>')
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='events')
    creator = models.ForeignKey(Account, on_delete=models.CASCADE)
    attendees = models.ManyToManyField(Account, related_name='attending', blank=True)
    num_of_attendees = models.PositiveIntegerField(default=0, blank=True)

    class Meta:
        verbose_name = 'event'
        verbose_name_plural = 'events'
        ordering = ['date', 'time']

    def get_absolute_url(self):
        return reverse('events:event-detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.name

    def get_number_of_attendees(self):
        return self.attendees.all().count()

    def get_comments_number(self):
        return self.comments.all().count()

meethub/events/forms.py
from django import forms

from meethub.events.models import Event, Category


class EventForm(forms.ModelForm):
    category = forms.ModelChoiceField(
        queryset=Category.objects.all(),
        empty_label="Select a category",
        widget=forms.Select(attrs={'class': 'form-control'})
    )

    class Meta:
        model = Event
        fields = ('category', 'name', 'details', 'venue', 'time', 'date',)
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'venue': forms.TextInput(attrs={'class': 'form-control'}),
            'date': forms.DateInput(attrs={'class': 'form-control', 'type': 'date'}),
            'time': forms.TimeInput(attrs={'class': 'form-control', 'type': 'time'}),
        }

meethub/events/views.py
from django.views import generic
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404, redirect
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.models import User
from django.views import View
from django.contrib.auth.decorators import login_required

from meethub.actions.utils import create_action
from meethub.comments.models import Comment
from meethub.comments.forms import CommentForm

from meethub.events.models import Event
from meethub.events.forms import EventForm


# Create your views here.


class EventList(LoginRequiredMixin, generic.ListView):
    model = Event
    template_name = 'events/list_of_events.html'
    context_object_name = 'events'
    paginate_by = 10

    def get_queryset(self):
        if self.request.user.is_superuser:
            return Event.objects.all()
        else:
            return Event.objects.all()


class EventDisplay(generic.DetailView):
    model = Event
    template_name = 'events/detail.html'
    context_object_name = 'event'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = CommentForm()
        context['comments'] = self.get_object().comments.all()
        context['attending'] = self.get_object().attendees.all
        return context


class CommentCreate(SuccessMessageMixin, generic.CreateView):
    model = Comment
    template_name = 'events/detail.html'
    fields = ('comment',)
    success_message = 'Comment was added successfully'

    def form_valid(self, form):
        form.instance = form.save(commit=False)
        form.instance.event = self.get_object(queryset=Event.objects.all())
        form.instance.created_by = self.request.user
        # create_action(self.request.user, 'added a comment', form.instance)
        form.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy('events:event-detail', kwargs={'pk': self.get_object(Event.objects.all()).pk})


class EventDetail(LoginRequiredMixin, View):

    def get(self, request, *args, **kwargs):
        view = EventDisplay.as_view()
        return view(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        view = CommentCreate.as_view()
        return view(request, *args, **kwargs)


class EventFormMixin(object):
    def form_valid(self, form):
        form.instance.creator = self.request.user
        response = super().form_valid(form)
        create_action(self.request.user, 'created a new event', form.instance)
        return response


class EventCreate(LoginRequiredMixin, SuccessMessageMixin, EventFormMixin, generic.CreateView):
    model = Event
    template_name = 'events/create_form.html'
    form_class = EventForm
    # fields = ('category', 'name', 'details', 'venue', 'time', 'date')
    context_object_name = 'event'
    success_message = "%(name)s was created successfully"

    
class EventUpdate(LoginRequiredMixin, SuccessMessageMixin, EventFormMixin, generic.UpdateView):
    model = Event
    template_name = 'events/update_form.html'
    template_name_suffix = '_update_form'
    fields = ('category', 'name', 'details', 'venue', 'time', 'date',)
    success_message = "%(name)s was updated successfully"


class EventDelete(LoginRequiredMixin, SuccessMessageMixin, generic.DeleteView):
    model = Event
    template_name = 'events/delete.html'
    success_url = reverse_lazy('events:event-list')
    context_object_name = 'event'
    success_message = "%(name)s was deleted successfully"


@login_required()
def attend_event(request, event_id):
    event = get_object_or_404(Event, pk=event_id)
    attendee = User.objects.get(username=request.user)
    event.attendees.add(attendee)
    create_action(attendee, 'is attending', event)
    messages.success(request, 'You are now attending {0}'.format(event.name))
    return redirect('events:event-detail', pk=event.pk)


@login_required()
def not_attend_event(request, event_id):
    event = get_object_or_404(Event, pk=event_id)
    attendee = User.objects.get(username=request.user)
    event.attendees.remove(attendee)
    create_action(attendee, 'no longer attending', event)
    messages.success(request, 'You are no longer attending {0}'.format(event.name))
    return redirect('events:event-detail', pk=event.pk)

meethub/events/templates/events/comment_reply.html
{% extends 'events/base.html' %}
{% load crispy_forms_filters %}
    {% block content %}
        <div class="mx-auto w-100">
      <form class="mx-auto w-50" method="post"> {% csrf_token %}
        {{ form|crispy }}
        <button class="mx-auto btn btn-primary btn-lg active w-25" type="submit">Add comment</button>
      </form>


    </div>

    {% endblock %}

meethub/events/templates/events/delete.html
{% extends 'events/base.html' %}

{% block title %}Delete {{ event.name }} - MeetHub{% endblock %}

{% block content %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-lg-6">
            <!-- Warning Header -->
            <div class="text-center mb-4">
                <div class="alert alert-warning border-0 shadow-sm">
                    <i class="fas fa-exclamation-triangle fa-3x text-warning mb-3"></i>
                    <h2 class="font-weight-bold text-dark mb-2">Confirm Deletion</h2>
                    <p class="mb-0">This action cannot be undone. Please proceed with caution.</p>
                </div>
            </div>

            <!-- Deletion Form -->
            <div class="card glass-card">
                <div class="card-header bg-transparent border-0 text-center py-4">
                    <h4 class="text-dark mb-0">
                        <i class="fas fa-trash-alt mr-2"></i>Delete Event
                    </h4>
                </div>
                
                <div class="card-body p-4">
                    <!-- Event Information -->
                    <div class="alert alert-light border mb-4">
                        <div class="row align-items-center">
                            <div class="col-md-8">
                                <h5 class="mb-2 text-dark">
                                    <i class="fas fa-calendar-alt mr-2"></i>{{ event.name }}
                                </h5>
                                <div class="text-muted">
                                    <small>
                                        <i class="fas fa-clock mr-1"></i>{{ event.date }} at {{ event.time }}
                                    </small>
                                    {% if event.venue %}
                                    <br>
                                    <small>
                                        <i class="fas fa-map-marker-alt mr-1"></i>{{ event.venue }}
                                    </small>
                                    {% endif %}
                                </div>
                            </div>
                            <div class="col-md-4 text-right">
                                <div class="text-muted">
                                    <i class="fas fa-users mr-1"></i>
                                    <span class="font-weight-bold">{{ event.get_number_of_attendees }}</span> attending
                                </div>
                            </div>
                        </div>
                    </div>

                    <!-- Warning Message -->
                    <div class="text-center mb-4">
                        <h5 class="text-danger mb-3">
                            <i class="fas fa-exclamation-circle mr-2"></i>
                            Are you sure you want to delete "{{ event.name }}"?
                        </h5>
                        <p class="text-muted mb-0">
                            This will permanently remove the event and all associated data. 
                            {% if event.get_number_of_attendees > 0 %}
                                <strong>{{ event.get_number_of_attendees }} attendee{{ event.get_number_of_attendees|pluralize }}</strong> will be notified about the cancellation.
                            {% endif %}
                        </p>
                    </div>

                    <!-- Consequences List -->
                    <div class="mb-4">
                        <h6 class="text-dark mb-3">
                            <i class="fas fa-list-ul mr-2"></i>What happens when you delete this event:
                        </h6>
                        <ul class="list-unstyled">
                            <li class="mb-2">
                                <i class="fas fa-times text-danger mr-2"></i>
                                The event will be permanently removed from MeetHub
                            </li>
                            <li class="mb-2">
                                <i class="fas fa-times text-danger mr-2"></i>
                                All comments and discussions will be deleted
                            </li>
                            {% if event.get_number_of_attendees > 0 %}
                            <li class="mb-2">
                                <i class="fas fa-bell text-warning mr-2"></i>
                                All attendees will receive a cancellation notification
                            </li>
                            {% endif %}
                            <li class="mb-2">
                                <i class="fas fa-times text-danger mr-2"></i>
                                This action cannot be undone
                            </li>
                        </ul>
                    </div>

                    <!-- Action Buttons -->
                    <form method="post" class="text-center">
                        {% csrf_token %}
                        <div class="row">
                            <div class="col-md-6 mb-3">
                                <a href="{% url 'events:event-detail' event.id %}" class="btn btn-outline-secondary btn-lg w-100">
                                    <i class="fas fa-arrow-left mr-2"></i>Keep Event
                                </a>
                            </div>
                            <div class="col-md-6 mb-3">
                                <button type="submit" class="btn btn-danger btn-lg w-100">
                                    <i class="fas fa-trash-alt mr-2"></i>Delete Forever
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>

            <!-- Safety Notice -->
            <div class="card glass-card mt-4">
                <div class="card-body text-center">
                    <h6 class="text-dark mb-3">
                        <i class="fas fa-shield-alt mr-2"></i>Need to make changes instead?
                    </h6>
                    <p class="text-muted mb-3">
                        If you're looking to update event details, consider editing instead of deleting.
                    </p>
                    <a href="{% url 'events:event-update' event.id %}" class="btn btn-primary">
                        <i class="fas fa-edit mr-2"></i>Edit Event Instead
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>

<style>
    .btn-lg {
        padding: 1rem 2rem;
        font-size: 1.1rem;
        font-weight: 600;
    }
    
    .alert-warning {
        background: linear-gradient(45deg, rgba(245, 158, 11, 0.1), rgba(251, 191, 36, 0.1));
        border: 1px solid rgba(245, 158, 11, 0.3);
        border-radius: 16px;
    }
    
    .alert-light {
        background: rgba(248, 250, 252, 0.8);
        border: 1px solid rgba(226, 232, 240, 0.8);
        border-radius: 12px;
    }

meethub/events/templates/events/detail.html
{% extends 'events/base.html' %}
{% load events_tags %}
{% load events_filters %}
{% load crispy_forms_filters %}
{% load cloudinary %}

{% block title %}{{ event.name }} - MeetHub{% endblock %}

{% block content %}
<div class="container">
    <!-- Event Header -->
    <div class="row mb-4">
        <div class="col-12">
            <div class="card glass-card">
                <div class="card-body p-4">
                    <div class="row align-items-center">
                        <div class="col-md-8">
                            <div class="d-flex align-items-center mb-3">
                                <div class="mr-3">
                                    <i class="fas fa-calendar-alt text-primary" style="font-size: 2rem;"></i>
                                </div>
                                <div>
                                    <h6 class="text-muted mb-1">
                                        <i class="fas fa-user-tie mr-1"></i>Organized by
                                    </h6>
                                    <h5 class="mb-0 text-primary font-weight-bold">{{ event.creator|capfirst }}</h5>
                                </div>
                            </div>
                            
                            <h1 class="display-4 font-weight-bold text-dark mb-3">{{ event.name }}</h1>
                            
                            <div class="row">
                                <div class="col-md-6 mb-2">
                                    <div class="d-flex align-items-center">
                                        <i class="fas fa-calendar text-primary mr-2"></i>
                                        <span class="h5 text-dark mb-0">{{ event.date }}</span>
                                    </div>
                                </div>
                                <div class="col-md-6 mb-2">
                                    <div class="d-flex align-items-center">
                                        <i class="fas fa-clock text-primary mr-2"></i>
                                        <span class="h5 text-dark mb-0">{{ event.time }}</span>
                                    </div>
                                </div>
                            </div>
                            
                            {% if event.venue %}
                            <div class="mt-3">
                                <div class="d-flex align-items-center">
                                    <i class="fas fa-map-marker-alt text-primary mr-2"></i>
                                    <span class="h6 text-dark mb-0">{{ event.venue }}</span>
                                </div>
                            </div>
                            {% endif %}
                        </div>
                        
                        <div class="col-md-4 text-center">
                            <div class="mb-3">
                                <div class="display-4 font-weight-bold text-primary">{{ event.get_number_of_attendees }}</div>
                                <div class="text-muted">People Attending</div>
                            </div>
                            
                            {% if request.user in attending %}
                                <a class="btn btn-danger btn-lg w-100 mb-3" href="{% url 'events:not_attend_event' event.id %}">
                                    <i class="fas fa-times mr-2"></i>Cancel Attendance
                                </a>
                            {% else %}
                                <a class="btn btn-success btn-lg w-100 mb-3" href="{% url 'events:attend_event' event.id %}">
                                    <i class="fas fa-check mr-2"></i>Join Event
                                </a>
                            {% endif %}
                            
                            {% if event.creator == request.user %}
                            <div class="btn-group w-100" role="group">
                                <a href="{% url 'events:event-update' event.id %}" class="btn btn-outline-primary">
                                    <i class="fas fa-edit mr-1"></i>Edit
                                </a>
                                <a href="{% url 'events:event-delete' event.id %}" class="btn btn-outline-danger">
                                    <i class="fas fa-trash mr-1"></i>Delete
                                </a>
                            </div>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Event Details -->
    <div class="row mb-4">
        <div class="col-12">
            <div class="jumbotron">
                <div class="container">
                    <h1 class="display-4 text-dark mb-4">
                        <i class="fas fa-info-circle mr-3"></i>Event Details
                    </h1>
                    <div class="lead text-dark">{{ event.details|safe }}</div>
                </div>
            </div>
        </div>
    </div>

    <!-- Attendees Section -->
    <div class="row mb-4">
        <div class="col-12">
            <div class="card glass-card">
                <div class="card-header bg-transparent border-0 pb-0">
                    <h2 class="text-dark mb-0">
                        <i class="fas fa-users mr-2"></i>{{ event.get_number_of_attendees }} Amazing People Attending
                    </h2>
                </div>
                <div class="card-body">
                    {% if attending %}
                        <div class="row">
                            {% for attendee in attending %}
                            <div class="col-md-4 col-sm-6 mb-3">
                                <div class="d-flex align-items-center p-3 border rounded">
                                    <div class="mr-3">
                                        <i class="fas fa-user-circle text-primary" style="font-size: 2rem;"></i>
                                    </div>
                                    <div>
                                        <h6 class="mb-0 font-weight-bold">{{ attendee.username|capfirst }}</h6>
                                        <small class="text-muted">Attendee</small>
                                    </div>
                                </div>
                            </div>
                            {% endfor %}
                        </div>
                    {% else %}
                        <div class="text-center py-5">
                            <i class="fas fa-users text-muted" style="font-size: 4rem;"></i>
                            <h4 class="text-muted mt-3">No one has joined yet</h4>
                            <p class="text-muted">Be the first to join this exciting event!</p>
                        </div>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>

    <!-- Comments Section -->
    <div class="row mb-4">
        <div class="col-12">
            <div class="card glass-card">
                <div class="card-header bg-transparent border-0 pb-0">
                    <h2 class="text-dark mb-0">
                        <i class="fas fa-comments mr-2"></i>{{ event.get_comments_number }} Comments
                    </h2>
                </div>
                <div class="card-body">
                    {% for comment in comments %}
                        {% if not comment.get_parents %}
                            <div class="media mb-4 p-3 border rounded">
                                <div class="media-object mr-3">
                                    {% cloudinary comment.get_comment_creator_photo width=50 height=50 radius='max' crop='fill' %}
                                </div>
                                <div class="media-body">
                                    <h5 class="mt-0 mb-2 text-primary font-weight-bold">{{ comment.created_by|capfirst }}</h5>
                                    <p class="text-dark mb-3">{{ comment.comment }}</p>
                                    <a href="{% url 'comments:comment-detail' comment.id event.id %}" class="btn btn-sm btn-outline-primary">
                                        <i class="fas fa-reply mr-1"></i>Reply
                                    </a>

                                    {% if comment.get_children %}
                                        <div class="mt-3">
                                            {% for child in comment.get_children %}
                                                <div class="media mt-3 ml-4 p-3 bg-light rounded">
                                                    <div class="media-object mr-3">
                                                        {% cloudinary child.get_comment_creator_photo width=40 height=40 radius='max' crop='fill' %}
                                                    </div>
                                                    <div class="media-body">
                                                        <h6 class="mt-0 mb-2 text-primary font-weight-bold">{{ child.created_by|capfirst }}</h6>
                                                        <p class="text-dark mb-2">{{ child.comment }}</p>
                                                        <a href="{% url 'comments:comment-detail' child.id event.id %}" class="btn btn-sm btn-outline-primary">
                                                            <i class="fas fa-reply mr-1"></i>Reply
                                                        </a>

                                                        {% if child.get_children %}
                                                            <div class="mt-3">
                                                                {% for grandchild in child.get_children %}
                                                                    <div class="media mt-2 ml-4 p-2 bg-white rounded border">
                                                                        <div class="media-object mr-2">
                                                                            {% cloudinary grandchild.get_comment_creator_photo width=30 height=30 radius='max' crop='fill' %}
                                                                        </div>
                                                                        <div class="media-body">
                                                                            <h6 class="mt-0 mb-1 text-primary font-weight-bold">{{ grandchild.created_by|capfirst }}</h6>
                                                                            <p class="text-dark mb-0">{{ grandchild.comment }}</p>
                                                                        </div>
                                                                    </div>
                                                                {% endfor %}
                                                            </div>
                                                        {% endif %}
                                                    </div>
                                                </div>
                                            {% endfor %}
                                        </div>
                                    {% endif %}
                                </div>
                            </div>
                        {% endif %}
                    {% empty %}
                        <div class="text-center py-5">
                            <i class="fas fa-comments text-muted" style="font-size: 4rem;"></i>
                            <h4 class="text-muted mt-3">No comments yet</h4>
                            <p class="text-muted">Start the conversation about this event!</p>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>

    <!-- Add Comment Form -->
    <div class="row mb-4">
        <div class="col-12">
            <div class="card glass-card">
                <div class="card-header bg-transparent border-0">
                    <h4 class="text-dark mb-0">
                        <i class="fas fa-plus-circle mr-2"></i>Join the Conversation
                    </h4>
                </div>
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <div class="mb-3">
                            {{ form|crispy }}
                        </div>
                        <button class="btn btn-primary btn-lg" type="submit">
                            <i class="fas fa-paper-plane mr-2"></i>Share Your Thoughts
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}